### PR TITLE
Update to the latest ML.NET 0.11.0-preview-27428-4.

### PR DESCRIPTION
**Pull request by eerhardt**
The biggest issue to overcome was in BinaryClassification. Two trainers (Perceptron and Linear SVM) don't produce Probabilities, which means they aren't "calibrated" and can't get a evaluated as such. With that, it means their metrics don't produce Entropy.

cc @XamlBrewer

### CODE REVIEW

**Comment by XamlBrewer** [comment]
Wow. This is impressive! Thank you very much! 
Please give me some time to digest this...

@eerhardt Wat would be a good time to merge this PR? I'll probably wait for your next official NuGet packages (ML and DataView), right?

**Comment by eerhardt** [comment]
Yes, I think if you'd like to wait for `v0.11`, which will be coming this week. Once `v0.11` has shipped officially on nuget.org, I can update this PR to that released version. Then you would be free to merge.

But please feel free to give PR feedback now. The `v0.11` APIs won't be changing from the version I am using - it is the "RC" build of `v0.11`. So the only known change would be to update the version from the preview to `0.11.0`.

**Comment by XamlBrewer** [comment]
Is the heat map OK in your project? I have a lot of NaN values in the input matrix (a lot in _Fare_ and **all** of the _Age_ values). Most of these values are correctly filled out in the data set. 

It looks like the DataView does not react properly to missing values, or to the commas in the passenger name. But maybe I'm just running against an invalid combination of experimental NuGet packages (ML, DataView, CpuMath).

**Comment by eerhardt** [comment]
No, I don't think the heat map is OK:

image

**Comment by eerhardt** [comment]
Looks like the problem was that we switched `AllowQuoting` from defaulting to `true` to now default to `false` with https://github.com/dotnet/machinelearning/commit/ec418e40408f09e239d56e07c470d00f3448fcc3.

I added `AllowQuoting = true,` and the map now looks like:

image

**Comment by XamlBrewer** [comment]
A build in _Release_ mode fails with "ilc.exe exited with code 1200". Is that because your daily packages at https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.ML  are debug builds? Or am I'm missing something?

**Comment by eerhardt** [comment]
I'm not sure. I tried looking into it and saw that it was raising an OutOfMemory error during `ilc.exe`. The daily builds of ML.NET are Release builds.

**Comment by eerhardt** [comment]
@XamlBrewer - I verified this is the same behvaior as building in `Release` mode in the master branch. It doesn't appear to be caused by my changes.

Are you seeing it in the master branch?

**Comment by eerhardt** [comment]
@XamlBrewer - ML.NET `v0.11.0` is now on nuget.org. I've pushed a commit to update to the released version.

**Comment by XamlBrewer** [comment]
When you create a new UWP project in Visual Studio and hook the new NuGet v0.11.0 ML.NET to it, you also get the ilc.exe fail on a Release build.

**Pull request merged**
